services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - .:/app
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'